name: Auto Merge PRs with 'automerge' Label

on:
  workflow_run:
    workflows: ["PR to Master"]  # name of your CI workflow
    types:
      - completed

jobs:
  automerge:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR info
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_WRITE_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              head: `${context.repo.owner}:dev`,
              base: "master"
            });

            const pr = prs.data.find(pr => pr.labels.some(label => label.name === 'automerge'));
            if (!pr) {
              console.log("No matching PR with 'automerge' label found.");
              return;
            }

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: "merge"
            });
