name: PR to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and Test
        run: ./mvnw clean verify

      - name: SonarQube Analysis
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=leultewolde_mereb_backend \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/mereb-backend:dev .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/mereb-backend:dev

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to LKE
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/mereb-backend

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/target/surefire-reports/*.xml'
